apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cheshire-cat
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log info;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        server_tokens off;

        server {
            listen 80;
            listen [::]:80;
            server_name localhost;
            client_max_body_size 1G;
            proxy_read_timeout 300s;
            proxy_connect_timeout 75s;
            
            add_header X-Frame-Options DENY always;
            add_header X-Content-Type-Options nosniff always;
            add_header X-XSS-Protection "1; mode=block" always;

            # Handle plugins endpoint with trailing slash for GET requests only
            location = /plugins {
                if ($request_method = GET) {
                    return 301 $scheme://$http_host/plugins/;
                }
                proxy_pass http://cheshire-cat-core:80/plugins/;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            
            location /plugins/ {
                proxy_pass http://cheshire-cat-core:80/plugins/;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            # Handle rabbithole endpoint - pass POST directly to /rabbithole/
            location = /rabbithole {
                if ($request_method = GET) {
                    return 301 $scheme://$http_host/rabbithole/;
                }
                # For POST requests, proxy directly to the trailing slash endpoint
                proxy_pass http://cheshire-cat-core:80/rabbithole/;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                
                # File upload specific settings
                proxy_request_buffering off;
                proxy_buffering off;
                client_max_body_size 1G;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
            }
            
            location /rabbithole/ {
                proxy_pass http://cheshire-cat-core:80/rabbithole/;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                
                # File upload specific settings
                proxy_request_buffering off;
                proxy_buffering off;
                client_max_body_size 1G;
                proxy_read_timeout 600s;
                proxy_send_timeout 600s;
            }

            location / {
                proxy_pass http://cheshire-cat-core:80;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /ws {
                proxy_pass http://cheshire-cat-core:80/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }

            location /static {
                alias /var/www/static;
                expires 30d;
                add_header Cache-Control "public, immutable";
            }

            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    } 