apiVersion: v1
kind: Service
metadata:
  name: cheshire-cat-core
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cheshire-cat-core
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.cheshireCat.port }}
    name: http
  selector:
    app: cheshire-cat-core 