apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ .Values.global.namespace }}
  labels:
    app: nginx
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 80
    name: http
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    app: nginx 