apiVersion: v1
kind: Secret
metadata:
  name: cheshire-cat-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app: cheshire-cat
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
  API_KEY_WS: {{ .Values.secrets.apiKeyWs | b64enc | quote }}
  QDRANT_API_KEY: {{ .Values.secrets.qdrantApiKey | b64enc | quote }} 